### ISSUE TITLE
What ever became of this idea?

### ISSUE THREAD

**Issue by jdblischak** [Thell/knitr-yaml-example#1]
I am interested in setting knitr options in an `_output.yaml` file that could then be used by all rmarkdown documents in a directory. After some searching I found your repo and like your example. In the [documentation](https://github.com/Thell/knitr-yaml-example/blob/master/man/provider1-package.Rd#L24), you state that you were working on a patch. However, your fork no longer exists and you never submitted a PR to the rmarkdown repo. Did you find an alternative solution? Were the rmarkdown developers receptive to this idea or not? I'd appreciate any advice since clearly you've thought about this issue.

**Comment by Thell** [comment]
It was shot down... https://github.com/rstudio/rmarkdown/issues/17#issuecomment-37461407

**Comment by jdblischak** [comment]
That's too bad. I think being able to specify knitr options in the yaml header would make it much easier to set quick formatting details, especially when these settings need to be shared across many files. I use an [_ouput.yaml](https://github.com/jdblischak/singleCellSeq/blob/gh-pages/analysis/_output.yaml) file to easily share `html_document` options across files, which is really nice, but then I have to maintain a separate [chunk-options.R](https://github.com/jdblischak/singleCellSeq/blob/master/analysis/chunk-options.R) file that I have to `source` at the beginning of each RMarkdown file in order to set a few common knitr options. One option would be to [create a custom format](http://rmarkdown.rstudio.com/developer_custom_formats.html), but creating an R package with the new function just to be able to set a few common knitr options is a high bar.

Thanks for making the attempt to simply this!
